spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping_list_android
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
